# Generated by Django 4.2.23 on 2025-08-25 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Register', '0002_alter_register_master_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminprofile_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Image')),
                ('Document', models.FileField(upload_to='Doc')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.register_master')),
            ],
        ),
    ]
