# Generated by Django 4.2.23 on 2025-09-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EhrAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile_master',
            name='Document',
            field=models.FileField(upload_to='Doc/'),
        ),
        migrations.AlterField(
            model_name='adminprofile_master',
            name='Image',
            field=models.ImageField(upload_to='Image/'),
        ),
    ]
