# Generated by Django 4.2.23 on 2025-08-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Master',
            fields=[
                ('Reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=40)),
                ('Mobile', models.CharField(max_length=12)),
                ('Password', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('Address', models.CharField(max_length=200)),
                ('Role_Name', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
