# Generated by Django 4.2.23 on 2025-09-03 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Register', '0002_alter_register_master_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientprofile_master',
            fields=[
                ('Patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('Diseases', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='Image/')),
                ('Document', models.FileField(upload_to='Doc/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.register_master')),
            ],
        ),
    ]
