# Generated by Django 4.2.23 on 2025-09-18 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_alter_register_master_email'),
        ('Staff', '0001_initial'),
        ('Patient', '0002_doctor_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTestReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.register_master')),
                ('tests', models.ManyToManyField(to='Staff.laboratory_test')),
            ],
        ),
    ]
